package exception;

public enum ErrorCode {
    TODO_DESCRIPTION_MISSING,
    DEADLINE_BY_MARKER_MISSING,
    DEADLINE_DESCRIPTION_MISSING,
    DEADLINE_BY_VALUE_MISSING,
    EVENT_FROM_MARKER_MISSING,
    EVENT_TO_MARKER_MISSING,
    EVENT_MARKERS_OUT_OF_ORDER,
    EVENT_DESCRIPTION_MISSING,
    EVENT_FROM_VALUE_MISSING,
    EVENT_TO_VALUE_MISSING,
    DUPLICATE_MARKER,
    TASK_ID_MISSING,
    TASK_ID_NOT_INTEGER,
    TASK_ID_NOT_POSITIVE,
    TASK_ID_TOO_LARGE,
    TASK_NOT_FOUND,
    UNEXPECTED_ARGUMENTS
}